My_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from home.views import home
from cv.views import cv

urlpatterns = [
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('article/',include(('article.urls',"article"),namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('home/',include('home.urls',namespace='home')),
    path('cv/',include('cv.urls',namespace='cv')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('cv/',views.cv,name='cv'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFit

from django.db.models.signals import post_save

from django.dispatch import receiver

# Create your models here.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name='profile')

    phone = models.CharField(max_length=20,blank=True)

    portrait = ProcessedImageField(
        upload_to='portrait/%Y%m%d',
        processors=[ResizeToFit(width=400,height=400)],
        options={'quality':100},
    )

    bio = models.TextField(max_length=600, blank=True)

    def __str__(self):
        return 'user{}'.format(self.user.username)

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserLogin(forms.Form):
    username = forms.CharField(max_length=32)
    password = forms.CharField(max_length=64)


class UserRegister(forms.ModelForm):
    password = forms.CharField(max_length=64)
    password2 = forms.CharField(max_length=64)

    class Meta:
        model = User
        fields = ('username','email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            raise forms.ValidationError("Inconsistent password input! Please try again")



class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone','portrait','bio')

userprofile/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate,login,logout
from .forms import UserLogin,UserRegister
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm
from .models import Profile


# Create your views here.
def user_login(request):
    if request.method == "POST":
        user_login_form = UserLogin(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            user = authenticate(username=data['username'],password=data['password'])
            if user:
                login(request,user)
                return redirect("article:article_list")
            else:
                return HttpResponse("Error:Username or password is wrong,please input again!")

        else:
            return HttpResponse("Error:Username or password disobeys the principle!")

    elif request.method == "GET":
        user_login_form = UserLogin()
        context = { 'form': user_login_form}
        return render(request,'userprofile/login.html',context)
    else:
        return HttpResponse("Please use Get or Post to request data!")


def user_logout(request):
    logout(request)
    return redirect("article:article_list")

def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegister(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save(commit=False)

            new_user.set_password(user_register_form.cleaned_data['password'])
            new_user.save()

            login(request,new_user)
            return redirect("article:article_list")
        else:
            return HttpResponse("Error:Register Form is wrong. Please input again!")

    elif request.method == 'GET':
        user_register_form = UserRegister()
        context = { 'form': user_register_form }
        return render(request,'userprofile/register.html',context)
    else:
        return HttpResponse("Please use GET or Post to request data!")


@login_required(login_url='/userprofile/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        if request.user == user:

            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("You do not have the right to delete")
    else:
        return HttpResponse("Only accept post request.")


@login_required(login_url='/userprofile/login/')
def profile_edit(request,id):
    user = User.objects.get(id=id)
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("You do not have the right to edit the user profile!")

        profile_form = ProfileForm(request.POST,request.FILES)
        if profile_form.is_valid():
            profile_cd = profile_form.cleaned_data
            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']
            if 'portrait' in request.FILES:
                profile.portrait = profile_cd["portrait"]
            profile.save()

            return redirect("userprofile:edit",id=id)
        else:
            return HttpResponse("The registered form is wrong! Please input again!")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = { 'profile_form': profile_form,'profile':profile,'user':user}
        return render(request,'userprofile/edit.html',context)
    else:
        return HttpResponse("Please use GET OR POST to request data.")

templates/userprofile/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}
User Profile
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">Username: {{ user.username }}</div>
            <br>
            {% if profile.portrait %}
                <div class="col-md-4">Portrait</div>
                <img src="{{ profile.portrait.url }}" style="max-width: 20%;border-radius:15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">No Portrait</h5>
            {% endif %}
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="portrait">Upload Portrait</label>
                    <input type="file" class="form-control" name="portrait" id="portrait">
                </div>

                <div class="form-group col-md-4">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>

                <div class="form-group col-md-4">
                    <label for="bio">Brief Introduction</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>

                <br>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>Have not have an account?</h5>
            <h5>Click<a href='{% url "userprofile:register" %}'> Register</a> to have one! </h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

            <br>
            <h5>Forget your password?</h5>
            <h5>Click <a href='{% url "password_reset_recover" %}'>Here</a> to reset password! </h5>

        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}

                <div class="form-group col-md-4">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>

                <div class="form-group col-md-4">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>

                <div class="form-group col-md-4">
                    <label for="password">Set Password</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>

                <div class="form-group col-md-4">
                    <label for="password2">Confirm your password</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}