My_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from home.views import home
from cv.views import cv

urlpatterns = [
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('article/',include(('article.urls',"article"),namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('home/',include('home.urls',namespace='home')),
    path('cv/',include('cv.urls',namespace='cv')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('cv/',views.cv,name='cv'),
]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [

    path('list/', views.CommentNoticeListView.as_view(), name='list'),

    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

notice/models.py
from django.db import models

# Create your models here.

notice/views.py
from django.shortcuts import render,redirect
from django.views import View
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from article.models import ArticlePost

# Create your views here.

class CommentNoticeListView(LoginRequiredMixin, ListView):

    context_object_name = 'notices'

    template_name = 'notice/list.html'

    login_url = '/userprofile/login/'

    # unread notifications query
    def get_queryset(self):
        return self.request.user.notifications.unread()


class CommentNoticeUpdateView(View):
    # update

    def get(self, request):
        # get unread notifications
        notice_id = request.GET.get('notice_id')
        # update single notification
        if notice_id:
            article = ArticlePost.objects.get(id=request.GET.get('article_id'))
            request.user.notifications.get(id=notice_id).mark_as_read()
            return redirect(article)
        # update all notifications
        else:
            request.user.notifications.mark_all_as_read()
            return redirect('notice:list')

templates/notice/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Notifications
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row mt-4 ml-4">
        <a href="{% url "notice:update" %}" class="btn btn-success" role="button">Clear all notifications</a>
    </div>
    <!-- Unread -->
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <a href="{% url "notice:update" %}?article_id={{ notice.target.id }}&notice_id={{ notice.id }}"
                       target="_blank"
                    >
                    <span style="color: #5897fb;">
                        {{ notice.actor }}
                    </span>
                        In <span style="color: #01a252;">{{ notice.target }}</span> {{ notice.verb }}.
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>




</div>

<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}