My_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from home.views import home
from cv.views import cv

urlpatterns = [
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('article/',include(('article.urls',"article"),namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('home/',include('home.urls',namespace='home')),
    path('cv/',include('cv.urls',namespace='cv')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article_create/',views.article_create,name='article_create'),
    path('article_safe_delete/<int:id>',views.article_safe_delete,name='article_safe_delete'),
    path('article_update/<int:id>/',views.article_update,name='article_update'),
]

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('cv/',views.cv,name='cv'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('home/',views.home,name='home'),

]

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [

    path('list/', views.CommentNoticeListView.as_view(), name='list'),

    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

comment/models.py
from django.db import models
from django.contrib.auth.models import User
from article.models import ArticlePost
from ckeditor.fields import RichTextField
from mptt.models import MPTTModel,TreeForeignKey

# Create your models here.

class Comment(MPTTModel):
    article = models.ForeignKey(
        ArticlePost,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    body = RichTextField()
    created = models.DateTimeField(auto_now_add=True)

    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children'
    )

    reply_to = models.ForeignKey(            # only allow secondary comment,exceed will be set secondary
        User,                                # reply_to store real one who was commented
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='replyers'
    )

    class MPTTMeta:
        order_insertion_by = ['created']

    def __str__(self):
        return self.body[:20]

cv/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.

class basicinfo(models.Model):
    college = models.CharField(max_length=100)
    major = models.CharField(max_length=100)
    edubg = models.CharField(max_length=100)
    age = models.IntegerField()
    birthplace = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    email = models.EmailField()
    wechat = models.CharField(max_length=100)

    def getcollege(self):
        return self.college

    def getage(self):
        return self.age

    def getemail(self):
        return self.email

class skills(models.Model):
    skills = models.CharField(max_length=100)

    def getskills(self):
        return self.skills

class interest(models.Model):
    interest = models.CharField(max_length=100)

    def getinterest(self):
        return self.interest

class eduexperience(models.Model):
    school = models.CharField(max_length=100)
    start = models.CharField(max_length=10)
    end = models.CharField(max_length=10)
    major = models.CharField(max_length=100,default="school")
    description = models.TextField()

    def getschool(self):
        return self.school

    def getstart(self):
        return self.start

class certificate(models.Model):
    time = models.CharField(max_length=20)
    name = models.CharField(max_length=100)

    def gettime(self):
        return self.time

    def getname(self):
        return self.name


class selfcomment(models.Model):
    comment = models.CharField(max_length=200)

    def getcomment(self):
        return self.comment

home/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

cv/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import basicinfo,skills,interest,eduexperience,certificate,selfcomment

# Create your views here.


def cv(request):
    infos = basicinfo.objects.get(id=1)
    skill_list = skills.objects.all()
    interest_list = interest.objects.all()
    eduex_list = eduexperience.objects.all()
    cert_list = certificate.objects.all()
    comment_list = selfcomment.objects.all()
    context = { 'infos': infos, 'skill_list':skill_list, 'interest_list':interest_list,
                'eduex_list':eduex_list, 'cert_list':cert_list, 'comment_list':comment_list}
    print(infos.college)
    return render(request,'cv.html',context)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.


def home(request):
    return render(request,"home.html")

templates/BacktoTop.html
<button type="button" id="BacktoTop" class="toTop-arrow" style="z-index:100;"></button>

<script>
    $(function () {
        $('#BacktoTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BacktoTop').fadeIn(300);
            } else {
                $('#BacktoTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>


<style>
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.8;
        background: rgb(85,143,83);
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: rgb(236,234,227);
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;

    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/default.css' %}">
</head>
<body background ="{% static 'images/bg4.png' %}">
    {% include 'header.html' %}
    <div id ="wrapper">
        {% block content %}{% endblock content %}
        <div id="push"></div>
    </div>
    {% include 'footer.html' %}
    <script src="{% static 'jquery/jquery.js' %}"></script>
    {% include 'BacktoTop.html' %}
    <script src="{% static 'poper/poper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'layer/layer.js' %}"></script>
    <script src="{% static 'ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'prism/prism.css' %}">
    <!-- icons -->
    <link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous">

    <style>
        html,body{
             height:100%;
             margin: 0;
        }
        #wrapper {
             min-height: 100%;
             margin-bottom: -60px;
        }

        #footer,
        #push {
            height: 60px;
        }
    </style>
    {% block script %}{% endblock script %}
</body>
</html>

templates/cv.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CV</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/default.css' %}">
    <script src="{% static 'poper/poper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body background ="{% static 'images/bg4.png' %}">
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;" >
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
            My_blog
        </a>
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Articles</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

    <br><br><br>
    <div style="width: 1500px;background-color: black;margin: -10px;height: 1px;"></div>
    <div class="row">
        <div class="col-md-7">
            <br><br><br>
            <h2 style="text-align:center">
                P E R S O N A L &nbsp;&nbsp;&nbsp;R E S U M E
            </h2>
            <h3 style="text-align:center">
                JINMAN &nbsp;ZHANG

            </h3>
            <h4 style="text-align:center">
                A CHANCE, A SURPRISE

            </h4><br>

            <h3 style="text-align:center">
                <i class="fas fa-book-open"></i>
                Education Experience<br>
            </h3>
            <h5>
                {% for eduex in eduex_list %}
                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="fas fa-archway"></i>
                    {{ eduex.school }}<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ eduex.major }}<br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;From year {{ eduex.start }} to year {{ eduex.end }}
                    <br>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ eduex.description }}
                </p>
                {% endfor %}
            </h5><br><br>

            <h3 style="text-align:center">
                <i class="fas fa-graduation-cap"></i>
                Certificate
            </h3>
            <h5 >
                {% for certificate in cert_list %}
                <p>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="far fa-bookmark"></i>
                    Year{{ certificate.time }}
                    {{ certificate.name }}
                </p>
                {% endfor %}
            </h5><br><br>

            <h3 style="text-align:center">
                <i class="fas fa-user-edit"></i>
                Self-assessment
            </h3>
            <h5>
                {% for comment in comment_list %}
                <p>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <i class="far fa-smile"></i>
                    {{ comment.comment }}
                </p>
                {% endfor %}
            </h5>

        </div>
        <div class="col-md-1">
            <br><br><br><br><br>
        <div style="width: 1px;background-color: black;margin: 0px;height: 1200px;"></div>
        </div>
        <div class="col-md-4" >
            <br><br>
            <img src="{% static 'images/白底一寸.jpg' %}" width="110" height="162" alt="" loading="lazy">
            <br><br>
            <div style="text-align:left">
                <h3>
                    <i class="fas fa-id-card"></i>
                    Basic Information
                </h3>
                <h5>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        College:&nbsp;{{ infos.college }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Major:&nbsp;{{ infos.major }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Education Background:&nbsp;{{ infos.edubg }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Age:&nbsp;{{ infos.age }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Birthplace:&nbsp;{{ infos.birthplace }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Phone Number:&nbsp;{{ infos.phone }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Email:&nbsp;{{ infos.email }}
                    </p>
                    <p>
                        <i class="fas fa-pencil-alt"></i>
                        Wechat:&nbsp;{{ infos.wechat }}
                    </p>
                </h5>
                <br><br>
                <h3>
                    <i class="far fa-thumbs-up"></i>
                    Professional Skills
                </h3>
                <h5>
                    {% for skill in skill_list %}
                    <p>
                        <i class="fas fa-tint"></i>
                        {{ skill.skills }}
                    </p>
                    {% endfor %}
                </h5>
                <br><br>
                <h3>
                    <i class="fas fa-heartbeat"></i>
                    Interests
                </h3>
                <h5>
                    {% for interest in interest_list %}
                    <p>
                        <i class="far fa-lemon"></i>
                        {{ interest.interest }}
                    </p>
                    {% endfor %}
                </h5>
            </div>
        </div>
    </div>


<footer class="py-3 " id="footer"  style="background-color: #e3f2fd;" >
    <div class="container">
        <p class="m-0 text-center text-pink">www.JinmanZhang.com 2020
        <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
        </p>
    </div>
</footer>

<link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous">
</body>
</html>

templates/footer.html
{% load static %}

<div>
    <br><br><br>
</div>

<footer class="py-3 " id="footer"  style="background-color: #e3f2fd;">
    <div class="container">
        <p class="m-0 text-center text-pink"> www.JinmanZhang.com 2020
        <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
        </p>
    </div>
</footer>

templates/header.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;" >
    <div class="container">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
            My_blog
        </a>
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:home' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cv:cv' %}">CV</a>
                </li>

                <li class="nav-item dropdown">      <!--the column,choose to find the columns'articles -->
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Column
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for column in columns %}
                            <a class="drop-item" name="column" href='{% url "article:article_list" %}?order={{ order }}&column={{ column }}'>{{ column.title }}</a><br>
                        {% endfor %}
                    </div>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Articles</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_create' %}">Write Articles</a>
                </li>
                {% if user.is_authenticated %}   <!--user login and logout -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                            ></circle>
                                    </svg>
                            {% endif %}

                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href='{% url "notice:list" %}'>Notifications
                                {% if unread_count %}
                                <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">Delete User</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>Log out</a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>User Profile</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'userprofile:login' %}">Login</a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %} <!--delete user -->
                <form
                    style="display:none;"
                    id="user_delete"
                    action="{% url 'userprofile:delete' user.id %}"
                    method="POST"
                >
                {% csrf_token %}              <!--re confirm -->
                    <button type="submit">Send</button>
                </form>
                    <script>
                        function user_delete(){
                            layer.open({
                                title:"Confirm delete",
                                content: "Do you confirm that you want to delete user data?",
                                yes: function(index,layero){
                                    $('form#user_delete button').click();
                                    layer.close(index);
                                },
                            })
                        }
                    </script>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home Page</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'md_css/default.css' %}">
    <script src="{% static 'poper/poper.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>
<body background="{% static 'images/bg4.png' %}" >
<!--<img id="bg" src="{% static 'images/bg1.bmp' %}" style="height:200px;width:100px;float:left;">-->
<h1  style="text-align:center">WELOCOME TO JINMANZHANG'S BLOG</h1>
<br><br><br>
<div class="row">
    <div class="col-md-3" style="text-align:center">
        <h3>
            JINMAN
            <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
            <br><br>
        </h3>
        <h4>
            <a href='{% url "home:home" %}'>Home</a>&nbsp;&nbsp;<i class="fas fa-home"></i><br><br>
            <a href='{% url "article:article_list" %}' >Blog</a>&nbsp;&nbsp;<i class="fab fa-fly"></i><br><br>
            <a href='{% url "cv:cv" %}'>CV</a>&nbsp;&nbsp;<i class="fas fa-file-alt"></i><br><br>
            <a href="https://github.com/zjmweb/My_blog">GitHub</a>&nbsp;&nbsp;<i class="fab fa-github"></i><br><br>
        </h4>
    </div>
    <div class="col-md-1">
        <div style="width: 1px;background-color: black;margin: -10px;height: 500px;"></div>
    </div>
    <div class="col-md-8" >
        <h4>
            <i class="far fa-hand-point-right"></i>
             Home
        </h4>
        <h5>
            The Home page is where you are right now. Here you can get some introduction to the blog<br>
            so that you can use it as soon as possible. The blog is designed for my second year coursework.
            <br><br>
        </h5>

        <h4>
            <i class="far fa-hand-point-right"></i>
            Blog
        </h4>
        <h5>
            The Blog is used for posting articles and communicating with others. Here every registered user<br>
            can post their articles, edit and delete it. The same applies to comments.<br><br>
            <h6>
                &nbsp;&nbsp;&nbsp;<i class="far fa-hand-point-down"></i>
                &nbsp;&nbsp;&nbsp;When creating articles, I strongly recommend that you use markdown to edit your article<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                since it has content part to help readers know the key points.<br>
            </h6>
            <!--<h6>
                &nbsp;&nbsp;&nbsp;<i class="far fa-hand-point-down"></i>
                &nbsp;&nbsp;&nbsp;When creating articles, the column is fixed, you can only choose.<br>
            </h6>-->
            <h6>
                &nbsp;&nbsp;&nbsp;<i class="far fa-hand-point-down"></i>
                &nbsp;&nbsp;&nbsp;When adding tags, please use English , to separate.<br>
            </h6>
        </h5>
        <br>
        <h4>
            <i class="far fa-hand-point-right"></i>
            CV
        </h4>
        <h5>
            Here you can view JINMAN ZHANG's personal CV.
        </h5>
        <br>
        <h4>
            <i class="far fa-hand-point-right"></i>
            Source Code
        </h4>
        <h5>
            Here you can view the Source Code.
        </h5>
    </div>

</div>
<div>
    <br><br>
</div>

<footer class="py-3 " id="footer"  style="background-color: #e3f2fd;" >
    <div class="container">
        <p class="m-0 text-center text-pink">www.JinmanZhang.com 2020
        <img src="{% static 'images/blogicon2.png' %}" width=40" height="40" alt="" loading="lazy">
        </p>
    </div>
</footer>

<link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous">

</body>
</html>