My_blog/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
import notifications.urls
from home.views import home
from cv.views import cv

urlpatterns = [
    path('',home,name='home'),
    path('admin/', admin.site.urls),
    path('article/',include(('article.urls',"article"),namespace='article')),
    path('userprofile/',include('userprofile.urls',namespace='userprofile')),
    path('password-reset/',include('password_reset.urls')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),
    path('notice/',include('notice.urls',namespace='notice')),
    path('home/',include('home.urls',namespace='home')),
    path('cv/',include('cv.urls',namespace='cv')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

article/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('article_list/',views.article_list,name='article_list'),
    path('article_detail/<int:id>/',views.article_detail,name='article_detail'),
    path('article_create/',views.article_create,name='article_create'),
    path('article_safe_delete/<int:id>',views.article_safe_delete,name='article_safe_delete'),
    path('article_update/<int:id>/',views.article_update,name='article_update'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path('post_comment/<int:article_id>/',views.post_comment,name='post_comment'),
    path('post_comment/<int:article_id>/<int:parent_comment_id>',views.post_comment,name='comment_reply'),
    path('delete_comment/<int:id>/',views.delete_comment,name='delete_comment'),
]

cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'

urlpatterns = [
    path('cv/',views.cv,name='cv'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout,name='logout'),
    path('register/',views.user_register,name='register'),
    path('delete/<int:id>/',views.user_delete,name='delete'),
    path('edit/<int:id>/',views.profile_edit,name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from PIL import Image
from taggit.managers import TaggableManager
from ckeditor.fields import RichTextField
# Create your models here.

class ArticleColumn(models.Model):
    title = models.CharField(max_length=100,blank=True)
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.title

class ArticlePost(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)

    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CharField,
        related_name='article'
    )

    body = models.TextField()
    tags = TaggableManager(blank=True)

    picture = models.ImageField(upload_to='article/%Y%m%d/', blank=True)  #deal with the picture when saving
    def save(self,*args,**kwargs):
        article = super(ArticlePost,self).save(*args,**kwargs)

        if self.picture and not kwargs.get('update_fields'):
            image = Image.open(self.picture)
            (x,y) = image.size
            new_x = 400
            new_y = int(new_x * (y/x))
            resized_image = image.resize((new_x,new_y),Image.ANTIALIAS)
            resized_image.save(self.picture.path)
        return article

    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    total_views = models.PositiveIntegerField(default=0)


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article:article_detail',args=[self.id])

    def was_created_recently(self):
        diff = timezone.now() - self.created
        if diff.days <= 0 and diff.seconds < 60:
            return True
        else:
            return False

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title','body','picture','tags')

article/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db import models
from .models import ArticlePost
import markdown
from .forms import ArticlePostForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from .models import ArticleColumn
from comment.forms import CommentForm

# Create your views here.
def article_list(request):        # display articles according to search,column,order
    search = request.GET.get('search')
    order = request.GET.get('order')
    columns = ArticleColumn.objects.all()  # for header to display columns(columns can only be created in admin)
    column = request.GET.get('column')
    columnid = ArticleColumn.objects.filter(title=column).first()

    tag = request.GET.get('tag')

    article_list = ArticlePost.objects.all()

    if search:
        article_list = ArticlePost.objects.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        search=''

    if column is not None:
        print(column)
        article_list=ArticlePost.objects.filter(Q(column_id=columnid))

    if tag and tag != 'None':
        article_list=article_list.filter(tags__name__in=[tag])

    if order == 'total_views':
        article_list=article_list.order_by('-total_views')

    paginator = Paginator(article_list, 3)
    page = request.GET.get('page')
    articles = paginator.get_page(page)

    context = {'articles': articles, 'order': order, 'search': search, 'columns': columns, 'column': column,'tag':tag,}

    return render(request, 'article/list.html', context)


def article_detail(request, id):
    article = ArticlePost.objects.get(id=id)
    comments = Comment.objects.filter(article=id)   # from comment app to display comments in the bottom of the article

    md = markdown.Markdown(
    extensions = [
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',

        'markdown.extensions.toc'
    ]
    )

    article.body = md.convert(article.body)
    article.total_views += 1
    article.save(update_fields=['total_views'])    # for the display method


    comment_form = CommentForm()
    context = {'article': article, 'toc':md.toc, 'comments': comments,'comment_form':comment_form,}

    return render(request, 'article/detail.html', context)


@login_required(login_url='userprofile/login/')       # only registered user can create article
def article_create(request):
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST,request.FILES)
        if article_post_form.is_valid():

            new_article = article_post_form.save(commit=False)

            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("Error:The content of form is wrong.Please fill out the form again")

    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article_post_form': article_post_form, 'columns': columns,}
        return render(request, 'article/create.html', context)


@login_required(login_url='userprofile/login/')  # only the author can delete and update
def article_safe_delete(request, id):
    articleget = ArticlePost.objects.get(id=id)    # get the current article
    user = articleget.author
    if request.user != user:
        return HttpResponse("You do not have the right to delete the article!")
    if request.method == 'POST':

        article = ArticlePost.objects.get(id=id)
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("Only allow post request")


@login_required(login_url='userprofile/login/')
def article_update(request, id):
    article = ArticlePost.objects.get(id=id)
    user = article.author
    if request.user != user:
        return HttpResponse("You do not have the right to delete the article!")
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None

            if request.FILES.get('picture'):
                article.picture = request.FILES.get('picture')

            article.title = request.POST['title']
            article.body = request.POST['body']
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("Error:The content of form is wrong.Please fill out the form again")

    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = {'article': article, 'article_post_form': article_post_form, 'columns': columns,}
        return render(request, 'article/update.html', context)

templates/article/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Write Articles
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="picture">Picture for article</label>
                    <input type="file" class="form-control-file" name="picture" id="picture">
                </div>

                <div class="form-group">
                    <label for="title">Article Title</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>

                <div class="form-group">
                    <label for="column">Column</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">Please choose column...</option>
                    {% for column in columns %}
                        <option value="{{ column.id }}">{{ column }}</option>
                    {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="tags">Label</label>
                    <input type="text"
                           class="form-control col-3"
                           id="tags"
                           name="tags">
                </div>

                <div class="form-group">
                    <label for="body">Article Content</label>
                    <textarea type="text"
                              class="form-control"
                              id = "body"
                              name = "body"
                              rows = "20"></textarea>
                </div>

                <button type="submit" class="btn btn-primary">Finish</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Full Content of Article
{% endblock title %}

{% block content %}

<div class="container" >
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>      <!--only author can see delete and update -->
                    author:  {{ article.author }}
                    {% if user == article.author %}
                         -<a href="#" onclick="confirm_safe_delete()">Delete</a>
                         -<a href="{% url "article:article_update" article.id %}">Edit Article</a>
                    {% endif %}
                </div>
                <div>
                    <div style="color:rgb(164,218,239)">
                         Readers:{{ article.total_views }}&nbsp;&nbsp;&nbsp;
                    </div>
                    <span style="color:rgb(249,187,192);">
                        {{ article.created|date:'Y-m-d' }} Post&nbsp;&nbsp;&nbsp;<br>
                    </span>
                    <span style="color:rgb(135,69,69);">
                        {{ article.updated|date:'Y-m-d' }} Update
                    </span>
                </div>
                <form
                    style="display:none;"
                    id="safe_delete"
                    action="{% url 'article:article_safe_delete' article.id %}"
                    method="POST"
                    >
                    {% csrf_token %}
                    <button type="submit">Send</button>
                </form>
            </div>

            <div>
                {{ article.body|safe }}
            </div>

            <hr>
            {% if user.is_authenticated %}       <!-- only registered user can comment the article-->
                <div>
                    <form action="{% url 'comment:post_comment' article.id %}" method="POST">
                        {% csrf_token %}
                            <div class="form-group">
                                <label for="body">
                                    <strong>
                                        Comment:
                                    </strong>
                                </label>
                                <div>
                                    {{ comment_form.media }}
                                    {{ comment_form.body }}
                                </div>
                            </div>

                            <button type="submit" class="btn btn-success">Post</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    Please<a href="{% url 'userprofile:login' %}">&nbsp;Login </a>&nbsp;First!
                </h5>
                <br>
            {% endif %}

            {% load mptt_tags %}
            <h4>{{ comments.count }} comments</h4>
            <div class="row">
                <!--traverse the tree structure-->
                {% recursetree comments %}

                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}">

                            <hr>
                            <p>
                                <strong style="color:pink">
                                    {{ comment.user }}
                                </strong>

                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right"
                                       style="color: cornflowerblue;"></i>
                                    <strong style="color:pink">
                                        {{ comment.reply_to }}
                                    </strong>
                                {% endif %}
                            </p>

                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color:rgb(135,69,69)">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!--load modal button-->
                                {% if user.is_authenticated %}
                                <button type="button"
                                        class="btn btn-light btn-sm text-muted"
                                        onclick="load_modal({{ article.id }}, {{ comment.id }})">
                                    Reply
                                </button>
                                {% else %}
                                <a class="btn btn-light btn-sm text-muted"
                                   href="{% url 'userprofile:login' %}">
                                    Reply
                                </a>
                                {% endif %}
                            </div>

                            <!--Modal-->
                            <div class="modal fade"
                                 id = "comment_{{ comment.id }}"
                                 tabindex="-1"
                                 role="dialog"
                                 aria-labelledby="CommentModalCenter"
                                 aria-hidden="true">

                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height:250px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">Reply {{ comment.user }}:</h5>
                                        </div>
                                        <div class="modal-boby" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>

                    {% endwith %}
                {% endrecursetree %}
            </div>

        </div>

        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>Content</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>

        <style>
            .sidebar{
            will-change: min-height;
            }

            .sidebar__inner{
            transform: translate(0, 0);
            transform: translate3d(0, 0, 0);
            will-change: position, transform;
            }

        </style>
    </div>

</div>

{% endblock content %}

{% block script %}

<script>
    function confirm_safe_delete(){
        layer.open({
            title:"Confirm Delete",
            btn:['Confirm'],
            content:"Do you confirm that you want to delete the article?",
            yes: function(index,layero){
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>

<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<script>
    // load modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // load editor
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post_comment/' +
                article_id +
                '/' +
                comment_id +
                '"' +
                ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' +
                comment_id +
                '"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    }
</script>

{% endblock script %}

templates/article/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Articles
{% endblock title %}

{% block content %}

<div class="container">                        <!--search article or find one column articles -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item" >
                {% if column %}
                    <a href="{% url 'article:article_list' %}?column={{ column }}">
                        Latest Article
                    </a>
                {% elif tag %}
                    <a href="{% url 'article:article_list' %}?tag={{ tag }}">
                        Latest Article
                    </a>
                {% else %}
                    <a href="{% url 'article:article_list' %}?search={{ search }}">
                        Latest Article
                    </a>
                {% endif %}
            </li>
            <li class="breadcrumb-item">
                {% if column %}
                    <a href="{% url 'article:article_list' %}?order=total_views&column={{ column }}">
                        Most Readers
                    </a>
                {% elif tag %}
                    <a href="{% url 'article:article_list' %}?order=total_views&tag={{ tag }}">
                        Most Readers
                    </a>
                {% else %}
                    <a href="{% url 'article:article_list' %}?order=total_views&search={{ search }}">
                       Most Readers
                    </a>
                {% endif %}
            </li>
        </ol>
    </nav>

    <div class="row">                <!--search box -->
        <div class="col-auto mr-auto">
            <form class="form-inline">
                <label class="sr-only">content</label>
                <input type="text"
                       class="form-control mb-2 mr-sm-2"
                       name="search"
                       placeholder="Search Articiles..."
                       required
                >
            </form>
        </div>
    </div>

    {% if search %}          <!--display introduction -->
        {% if articles %}
            <h4><span style="color:green;font-size=36px;">"{{ search }}"</span> related results as follows: </h4>
            <hr>
        {% else %}
            <h4>No such intention<span style="color:green;font-size=36px;">"{{ search }}</span> related to searched articles. </h4>
            <hr>
        {% endif %}
    {% endif %}

    <div class="row mt-2">
        {% for article in articles %}
        <!--Picture for articles-->
            {% if article.picture %}
                <div class="col-3">
                    <img src="{{ article.picture.url }}"
                         alt="picture"
                         style="max-width:100%; border-redius:20px"
                    >
                </div>
            {% endif %}

            <!-- content -->
            <div class="col">
                {% if article.column %}
                    <a name="column" href='{% url "article:article_list" %}?column={{ article.column }}' class="btn btn-sm mb-2 btn-outline-success">
                        {{ article.column }}
                    </a>
                {% endif %}
                &nbsp;&nbsp;&nbsp;
                <span>
                    {% for tag in article.tags.all %}
                        <a href="{% url 'article:article_list' %}?tag={{ tag }}" class="badge badge-info">
                            {{ tag }}
                        </a>
                    {% endfor %}
                </span>

                <h4>
                    <b>
                        <a href="{% url 'article:article_detail' article.id %}" style="color:black;">
                            {{ article.title }}
                        </a>
                    </b>
                </h4>

                <div>
                    <p style="color:grey;">
                        {{ article.body|slice:'100'}}...
                    </p>
                </div>

                <p>
                <!-- readers,post&update-->
                    <span>
                        <i class="fas fa-eye" style="color:rgb(133,215,245)"></i>
                        {{ article.total_views }} &nbsp;&nbsp;&nbsp;
                    </span>

                    <span>
                        <i class="fas fa-comments" style="color:rgb(85,143,83)"></i>
                        {{ article.comments.count }}&nbsp;&nbsp;&nbsp;
                    </span>

                    <span>
                        <i class="fas fa-clock" style="color:pink"></i>
                        {{ article.created|date:'Y-m-d' }} &nbsp;&nbsp;&nbsp;&nbsp;
                    </span>

                    <span>
                        <i class="fas fa-clock" style="color:rgb(135,69,69)"></i>
                        {{ article.updated|date:'Y-m-d' }}
                    </span>
                </p>
            </div>
                <hr style="width:100%;"/>
        {% endfor %}
    </div>

</div>



<div class="pagination row">           <!--page button -->
    <div class="m-auto">
        <span class="step-links">
            {% if articles.has_previous %}
                {% if column %}
                    <a href="?page=1&order={{ order }}&column={{ column }}" class="btn btn-success">
                     &laquo;1
                     </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&column={{ column }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% elif tag %}
                    <a href="?page=1&order={{ order }}&tag={{ tag }}" class="btn btn-success">
                     &laquo;1
                     </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% else %}
                    <a href="?page=1&order={{ order }}&search={{ search }}" class="btn btn-success">
                     &laquo;1
                     </a>
                    <span>...</span>
                    <a href="?page={{ articles.previous_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ articles.previous_page_number }}
                    </a>
                {% endif %}
            {% endif %}

            <span class="current btn btn-info btn-lg">
                {{ articles.number }}
            </span>

            {% if articles.has_next %}
                {% if column %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&column={{ column }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&column={{ column }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% elif tag %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&tag={{ tag }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&tag={{ tag }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% else %}
                    <a href="?page={{ articles.next_page_number }}&order={{ order }}&search={{ search }}" class="btn btn-secondary">
                        {{ articles.next_page_number }}
                    </a>
                    <span>...</span>
                    <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}&search={{ search }}" class="btn btn-success">
                        {{ articles.paginator.num_pages }} &raquo;
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

templates/article/update.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Update Articles
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">Article Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <div class="form-group">
                    <label for="picture">Picture for article</label>
                    <input type="file" class="form-control-file" name="picture" id="picture">
                </div>

                <div class="form-group">
                    <label for="column">Column</label>
                    <select class="form-control" id="column" name="column">
                        <option value="none">Please choose columns...</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                    {% if column.id == article.column.id %}
                                        selected
                                    {% endif %}
                                    >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>


                <div class="form-group">
                    <label for="body">Article Content</label>
                    <textarea type="text"
                              class="form-control"
                              id = "body"
                              name = "body"
                              rows = "20">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">Finish</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}